### ISSUE TITLE
SSH login is not possible  for sama5d4_xplained_demo_defconfig

### ISSUE THREAD

**Issue by jensamberg** [linux4sam/buildroot-external-microchip#1]
SSH login is not possible. My host says.
root@192.168.0.15's password: 
Permission denied, please try again.
Have I to do additional steps?

Is it correct that both is on dropbear and OPENSSH?

BR2_PACKAGE_DROPBEAR=y
BR2_PACKAGE_DROPBEAR_DISABLE_REVERSEDNS=y
BR2_PACKAGE_OPENSSH=y

**Comment by joshua-henderson** [comment]
By default dropbear does not allow an empty root password.  It simply refuses to accept one - even if that *is* root's password.  This is a good idea for many reasons.   To login with ssh, you need to set a password through a serial terminal using the passwd command.  Or, if you are building your own image with buildroot you can set the default password for root in menuconfig.  In any event, with a non-empty password ssh will then work.

**Comment by jensamberg** [comment]
@joshua-henderson  Sorry this is not correct. I trie it and does not work. But I found the bug and also the solution

1. Please check directory /etc/init.d. There is S50dropbear and S50sshd inside
2. So two different ssh server are started.
3. After remove S50dropbesar from /etc/init.d
4. Modify the sshd_config in /etc/ssh and add the line  PermitRootLogin yes

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
PermitRootLogin yes
#StrictModes yes
#MaxAuthTries 6



Please try yourself otherwise ssh with Ubuntu 18.04 is not possible.
