### ISSUE TITLE
NodeJS is slow to startup

### ISSUE THREAD

**Issue by robertdeml** [linux4sam/buildroot-external-microchip#10]
When I run NodeJS on an empty script, it takes 26 seconds to complete:
time node -e ""

If I download, unpack and run a precompiled NodeJS from [https://nodejs.org/download/release/latest-v15.x/node-v15.3.0-linux-armv7l.tar.gz], it takes 2 seconds to complete.

I can print the configuration that each node was built with with 'node -e "console.log(process.config)" '

The Slow Node has this configuration:
{
  target_defaults: {
    cflags: [],
    default_configuration: 'Release',
    defines: [],
    include_dirs: [],
    libraries: [
      '-L/home/rdeml/microchip/buildroot-at91/output/host/bin/../arm-buildroot-linux-gnueabihf/sysroot/usr/lib',
      '-lz',
      '-L/home/rdeml/microchip/buildroot-at91/output/host/bin/../arm-buildroot-linux-gnueabihf/sysroot/usr/lib',
      '-luv',
      '-L/home/rdeml/microchip/buildroot-at91/output/host/bin/../arm-buildroot-linux-gnueabihf/sysroot/usr/lib',
      '-lcares',
      '-L/home/rdeml/microchip/buildroot-at91/output/host/bin/../arm-buildroot-linux-gnueabihf/sysroot/usr/lib',
      '-lnghttp2',
      '-L/home/rdeml/microchip/buildroot-at91/output/host/bin/../arm-buildroot-linux-gnueabihf/sysroot/usr/lib',
      '-lcrypto',
      '-lssl'
    ]
  },
  variables: {
    arm_float_abi: 'hard',
    arm_fpu: 'vfpv3-d16',
    arm_thumb: 0,
    arm_version: '7',
    asan: 0,
    build_v8_with_gn: false,
    coverage: false,
    dcheck_always_on: 0,
    debug_nghttp2: false,
    debug_node: false,
    enable_lto: false,
    enable_pgo_generate: false,
    enable_pgo_use: false,
    force_dynamic_crt: 0,
    host_arch: 'arm',
    icu_small: false,
    is_debug: 0,
    llvm_version: '0.0',
    napi_build_version: '6',
    node_byteorder: 'little',
    node_debug_lib: false,
    node_enable_d8: false,
    node_install_npm: true,
    node_module_version: 72,
    node_no_browser_globals: false,
    node_prefix: '/usr',
    node_release_urlbase: '',
    node_shared: false,
    node_shared_brotli: false,
    node_shared_cares: true,
    node_shared_http_parser: false,
    node_shared_libuv: true,
    node_shared_nghttp2: true,
    node_shared_openssl: true,
    node_shared_zlib: true,
    node_tag: '',
    node_target_type: 'executable',
    node_use_bundled_v8: true,
    node_use_dtrace: false,
    node_use_etw: false,
    node_use_node_code_cache: false,
    node_use_node_snapshot: false,
    node_use_openssl: true,
    node_use_v8_platform: true,
    node_with_ltcg: false,
    node_without_node_options: false,
    openssl_fips: '',
    openssl_is_fips: false,
    shlib_suffix: 'so.72',
    target_arch: 'arm',
    v8_enable_gdbjit: 0,
    v8_enable_i18n_support: 0,
    v8_enable_inspector: 0,
    v8_enable_lite_mode: 0,
    v8_no_strict_aliasing: 1,
    v8_optimized_debug: 1,
    v8_promise_internal_field_count: 1,
    v8_random_seed: 0,
    v8_trace_maps: 0,
    v8_use_siphash: 1,
    v8_use_snapshot: 0,
    want_separate_host_toolset: 0
  }
}

The fast Node has this config:
{
  target_defaults: {
    cflags: [],
    default_configuration: 'Release',
    defines: [],
    include_dirs: [],
    libraries: []
  },
  variables: {
    arm_float_abi: 'hard',
    arm_fpu: 'vfpv3',
    arm_thumb: 0,
    arm_version: '7',
    asan: 0,
    coverage: false,
    dcheck_always_on: 0,
    debug_nghttp2: false,
    debug_node: false,
    enable_lto: false,
    enable_pgo_generate: false,
    enable_pgo_use: false,
    error_on_warn: false,
    experimental_quic: false,
    force_dynamic_crt: 0,
    gas_version: '2.28',
    host_arch: 'ia32',
    icu_data_in: '../../deps/icu-tmp/icudt67l.dat',
    icu_endianness: 'l',
    icu_gyp_path: 'tools/icu/icu-generic.gyp',
    icu_path: 'deps/icu-small',
    icu_small: false,
    icu_ver_major: '67',
    is_debug: 0,
    llvm_version: '0.0',
    napi_build_version: '7',
    node_byteorder: 'little',
    node_debug_lib: false,
    node_enable_d8: false,
    node_install_npm: true,
    node_module_version: 88,
    node_no_browser_globals: false,
    node_prefix: '/',
    node_release_urlbase: 'https://nodejs.org/download/release/',
    node_section_ordering_info: '',
    node_shared: false,
    node_shared_brotli: false,
    node_shared_cares: false,
    node_shared_http_parser: false,
    node_shared_libuv: false,
    node_shared_nghttp2: false,
    node_shared_openssl: false,
    node_shared_zlib: false,
    node_tag: '',
    node_target_type: 'executable',
    node_use_bundled_v8: true,
    node_use_dtrace: false,
    node_use_etw: false,
    node_use_node_code_cache: false,
    node_use_node_snapshot: false,
    node_use_openssl: true,
    node_use_v8_platform: true,
    node_with_ltcg: false,
    node_without_node_options: false,
    openssl_fips: '',
    openssl_is_fips: false,
    ossfuzz: false,
    shlib_suffix: 'so.88',
    target_arch: 'arm',
    v8_enable_31bit_smis_on_64bit_arch: 0,
    v8_enable_gdbjit: 0,
    v8_enable_i18n_support: 1,
    v8_enable_inspector: 1,
    v8_enable_lite_mode: 0,
    v8_enable_object_print: 1,
    v8_enable_pointer_compression: 0,
    v8_no_strict_aliasing: 1,
    v8_optimized_debug: 1,
    v8_promise_internal_field_count: 1,
    v8_random_seed: 0,
    v8_trace_maps: 0,
    v8_use_siphash: 1,
    want_separate_host_toolset: 1
  }
}

Probably the biggest difference is the version.  The Slow Node is at 12.18.4.  The fast Node is at 15.3.0.  The current LTS version is 14.15.1.  It also runs fast.

Can we update the nodejs make file to download and build 14.15.1?

**Comment by ehristev** [comment]
Hi,

Which version of buildroot are you using with our external tree ?
And which Makefile do you refer to ?

Eugen

**Comment by noglitch** [comment]
FYI, in YP with dunfell branch we are blocked with 12.14.1.

**Comment by robertdeml** [comment]
> Which version of buildroot are you using with our external tree ?

I followed these instructions:
git clone https://github.com/linux4sam/buildroot-external-microchip.git -b 2020.02-at91
git clone https://github.com/linux4sam/buildroot-at91.git -b 2020.02-at91
cd buildroot-at91
BR2_EXTERNAL=../buildroot-external-microchip/ make sama5d4_xplained_graphics_defconfig
make

So, I'm assuming the buildroot is at branch 2020.02-at91.

> And which Makefile do you refer to ?

The Makefile that I was referring to is:
.\buildroot-at91\package\nodejs\nodejs.mk

I tried to change the version number in that file to 14.15.1 and add the hash to nodejs.hash for that version, but I ran into another problem with python:
ImportError: No module named bz2

I think the host python 2.7.18 needs to have the bzip module built or imported.

**Comment by ehristev** [comment]
I had a quick look in upstream official buildroot repository, and it looks like even in the latest newest buildroot release (2020.11 which was released 2 days ago), the nodejs is still at version 12.18.4 ( https://git.buildroot.net/buildroot/tree/package/nodejs/nodejs.mk )
It looks like buildroot upstream has not moved to a newer major version of nodejs, and probably there is a good reason for that. (and this reason is not in my knowledge). 
I believe that buildroot may update the nodejs to 14.x in the future, but I cannot say when. We are bound to use this distribution from buildroot, so, what they provide right now is the best that we can further provide to you.
I suggest that you send a mail to the buildroot mailing list , or check through the mailing list archives to see if they plan any updates, or, you have to figure out yourself how to upgrade to 14.x, as you may need additional dependencies which are unmet in neither of 2020.02 nor 2020.11 .
We can only help by providing the original packets that vanilla buildroot comes with, and help with the packages that we currently have in our microchip external tree.
Hope that somehow this might help,
Eugen

**Comment by robertdeml** [comment]
Eugen, thank you for the explanation. It looks like I'll have to push on the buildroot side instead of the microchip side.  On a positive note, by fixing it in the buildroot, it will help many more people.
