### ISSUE TITLE
linux4sam build problem following microchip u embedded linux course

### ISSUE THREAD

**Issue by jamesscaggs** [linux4sam/buildroot-external-microchip#11]
I'm following along with the microchip U course here: https://mu.microchip.com/introduction-to-embedded-linux/606419

I have made it to the step where we need to make the images but I'm getting this error:

```
make[1]: *** [package/pkg-generic.mk:250: /home/jamesscaggs/Downloads/buildroot-at91/output/build/host-gcc-initial-9.3.0/.stamp_built] Error 2

make: *** [Makefile:84: _all] Error 2
```

I've already tried this fix: https://www.linux4sam.org/bin/view/Linux4SAM/BuildIssueOpenWrtUbuntu2004

I'm really just wanting to build the images so I can look for the device tree file to better understand the structure.

Any help is appreciated

**Comment by ehristev** [comment]
Hi,
I was out of office, I am back now and can help you out.
Could you please attach the whole build log... I need to see the context of where it's stuck .
Which host Linux you have ? Ubuntu 20.04 ?

**Comment by jamesscaggs** [comment]
Which host Linux you have ? Ubuntu 20.04 ?


Hello, I finally figured it out. I don't remember exactly what was wrong
but I got it sorted out. You can close this issue. Thanks,

James Scaggs

Sent via Superhuman ***@***.***>
