### ISSUE TITLE
linux4sam/buildroot-extern-microchip do not build sdcard.img

### ISSUE THREAD

**Issue by helloworld1234567891** [linux4sam/buildroot-external-microchip#12]
linux4sam/buildroot-extern-microchip do not build sdcard.img,but build uboot,zimage,rootfs is well. sea the picture.
![J~94_VGB@~0W`~17I346W T](https://user-images.githubusercontent.com/38292139/129337260-03e1d351-e6ae-43ec-a9e8-4bea9358bc55.png)
![A~UB~5_E4YNXB}F75455PDS](https://user-images.githubusercontent.com/38292139/129337269-06607776-d934-42ba-8f89-d77c0f70be96.png)

**Comment by ehristev** [comment]
Hi,

It looks to me like you build a configuration of buildroot for ***nand flash*** and ***not*** for SD-Card.
Can you share which config you used ?
(before you started the build, you ran 'make <...>_defconfig' , I need to know which defconfig was it )

**Comment by helloworld1234567891** [comment]
git clone git://github.com/linux4sam/buildroot-external-microchip.git git clone git://github.com/linux4sam/buildroot-at91.git cd buildroot-at91BR2_EXTERNAL=../buildroot-external-microchip/ Sudo make at91sam9g45m10ek_defconfig Sudo make
not other operate.picture is the result!





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eugen ***@***.***&gt;; 
发送时间: 2021年8月16日(星期一) 下午5:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [linux4sam/buildroot-external-microchip] linux4sam/buildroot-extern-microchip do not build sdcard.img (#12)





 
Hi,
 
It looks to me like you build a configuration of buildroot for nand flash and not for SD-Card.
 Can you share which config you used ?
 (before you started the build, you ran 'make <...&gt;_defconfig' , I need to know which defconfig was it )
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ehristev** [comment]
at91sam9g45m10ek_defconfig is a configuration for NAND flashes not for SD-Card, so , you will not obtain sdcard.img 
in buildroot-at91 configs/ directory , only configurations that have **mmc** in the file name, are done for sd-card.
What you can do, is after
_make at91sam9g45m10ek_defconfig_ 
do 
_make menuconfig_
then try to change the destination of the root file system from NAND to SD-Card and rebuild

**Comment by ehristev** [comment]
Images that have a NAND flash destination , are supposed to be flashed into the NAND flash , 
so of course, you will get a bootloader, a linux image, and a rootfs.tar, but you will not get the img file as you do not need it for NAND. you will get a ubifs file that is already ubinized for flashing onto the board

**Comment by helloworld1234567891** [comment]
thanks，i am try on tomorrow。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eugen ***@***.***&gt;; 
发送时间: 2021年8月16日(星期一) 下午5:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [linux4sam/buildroot-external-microchip] linux4sam/buildroot-extern-microchip do not build sdcard.img (#12)






at91sam9g45m10ek_defconfig是一个 NAND 闪存配置，而不是 SD 卡，因此，您将无法获得 sd card . img
在 build root - at 91 config / directory 中，只有具有mmc在文件名中，都是为 sd - card 做的。
你能做的，是后
制造at91sam9g45m10ek_defconfig
做
制作菜单配置
然后尝试将根文件系统的目标从 NAND 更改为 SD - Card 并重建

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by helloworld1234567891** [comment]
i am get a GTAG line and sam-ba 2.12 reinstall the OS, the files is from&nbsp;ftp://www.linux4sam.org/pub/demo/linux4sam_4.2/linux4sam-buildroot-at91sam9m10g45ek-4.2.zip,but it do not working, the screen is view the picture like BIOS start working,but 1 seconds later,the at91sam9m10g45ek is trun off.so ,can you give me a solution of this!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linux4sam/buildroot-external-microchip"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 下午5:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linux4sam/buildroot-external-microchip] linux4sam/buildroot-extern-microchip do not build sdcard.img (#12)





 
at91sam9g45m10ek_defconfig is a configuration for NAND flashes not for SD-Card, so , you will not obtain sdcard.img
 in buildroot-at91 configs/ directory , only configurations that have mmc in the file name, are done for sd-card.
 What you can do, is after
 make at91sam9g45m10ek_defconfig
 do
 make menuconfig
 then try to change the destination of the root file system from NAND to SD-Card and rebuilt
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ehristev** [comment]
Regarding this, I cannot help. I do not have the sam9m10g45 ek at my disposal. You would have to open a support ticket on http://support.microchip.com and someone will help you there. 
The boards that we currently support in linux4sam are : sam9x60ek, sama5d2_icp, sama5d2_xplained, sama5d3_xplained, sama5d4_xplained, sama5d27_som1_ek, sama5d27_wlsom1_ek, sama7g5_ek, sama5d2_ptc_ek

**Comment by helloworld1234567891** [comment]
ok,thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linux4sam/buildroot-external-microchip"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linux4sam/buildroot-external-microchip] linux4sam/buildroot-extern-microchip do not build sdcard.img (#12)





 
Regarding this, I cannot help. I do not have the sam9m10g45 ek at my disposal. You would have to open a support ticket on http://support.microchip.com and someone will help you there.
 The boards that we currently support in linux4sam are : sam9x60ek, sama5d2_icp, sama5d2_xplained, sama5d3_xplained, sama5d4_xplained, sama5d27_som1_ek, sama5d27_wlsom1_ek, sama7g5_ek, sama5d2_ptc_ek
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by helloworld1234567891** [comment]
now，the supur terminal can used this,but the LCD screen is nothing view,do you know why?but the uboot can view on the LCD screen.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linux4sam/buildroot-external-microchip"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linux4sam/buildroot-external-microchip] linux4sam/buildroot-extern-microchip do not build sdcard.img (#12)





 
Regarding this, I cannot help. I do not have the sam9m10g45 ek at my disposal. You would have to open a support ticket on http://support.microchip.com and someone will help you there.
 The boards that we currently support in linux4sam are : sam9x60ek, sama5d2_icp, sama5d2_xplained, sama5d3_xplained, sama5d4_xplained, sama5d27_som1_ek, sama5d27_wlsom1_ek, sama7g5_ek, sama5d2_ptc_ek
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by helloworld1234567891** [comment]
i known why the at91sam9m10-g45 do not have lcd screen，because i download the images on the&nbsp;ftp://www.linux4sam.org/pub/demo/linux4sam_4.2/linux4sam-buildroot-at91sam9m10g45ek-4.2.zip ，this images is smallist linux os， do not have the lcd screen system software。so can you give me a linking to download the have lcd screen system software‘s images like the link ftp://www.linux4sam.org/pub/demo/linux4sam_4.2/linux4sam-buildroot-at91sam9m10g45ek-4.2.zip 。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linux4sam/buildroot-external-microchip"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linux4sam/buildroot-external-microchip] linux4sam/buildroot-extern-microchip do not build sdcard.img (#12)





 
Closed #12.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ehristev** [comment]
Can you open another issue. This is completely unrelated to the initial problem, which looks now solved.

**Comment by helloworld1234567891** [comment]
yes，this question is resolved！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linux4sam/buildroot-external-microchip"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月18日(星期三) 晚上6:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linux4sam/buildroot-external-microchip] linux4sam/buildroot-extern-microchip do not build sdcard.img (#12)





 
Can you open another issue. This is completely unrelated to the initial problem, which looks now solved.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
