### ISSUE TITLE
mkimage: unsupported type Flat Device Tree

### ISSUE THREAD

**Issue by klmchp** [linux4sam/buildroot-external-microchip#13]
Hi ,
There was an error message showing as following when I tried to use buildroot-external-microchip-linux4sam-2021.04 with buildroot-at91-linux4sam-2021.04 to generate a ROOTFS for SAM9X60-EK. I used the default configuration for SAM9X60-EK and it failed at generating sam9x60.itb file.
~/atmel/egt/buildroot-at91-linux4sam-sam9x60-2021.04$ make
>>> dt-overlay-at91 linux4sam-2021.04 Building
PATH="/home/kevin/atmel/egt/buildroot-at91-linux4sam-sam9x60-2021.04/output/build/linux-linux4sam-2021.04/scripts/dtc:/home/kevin/atmel/egt/buildroot-at91-linux4sam-sam9x60-2021.04/output/host/bin:/home/kevin/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/microchip/xc32/v2.10/bin:/opt/microchip/xc32/v2.15/bin:/opt/microchip/xc32/v2.20/bin:/opt/microchip/xc32/v2.10/bin:/opt/microchip/xc32/v2.15/bin:/opt/microchip/xc32/v2.20/bin" /usr/bin/make -j5 DTC="/home/kevin/atmel/egt/buildroot-at91-linux4sam-sam9x60-2021.04/output/build/linux-linux4sam-2021.04/scripts/dtc/dtc" KERNEL_DIR="/home/kevin/atmel/egt/buildroot-at91-linux4sam-sam9x60-2021.04/output/build/linux-linux4sam-2021.04" -C /home/kevin/atmel/egt/buildroot-at91-linux4sam-sam9x60-2021.04/output/build/dt-overlay-at91-linux4sam-2021.04 "sam9x60ek".itb
mkimage -D "-i/home/kevin/atmel/egt/buildroot-at91-linux4sam-sam9x60-2021.04/output/build/linux-linux4sam-2021.04/arch/arm/boot/ -i/home/kevin/atmel/egt/buildroot-at91-linux4sam-sam9x60-2021.04/output/build/linux-linux4sam-2021.04/arch/arm/boot/dts -p 1000 -@ -Wno-unit_address_vs_reg -Wno-graph_child_address -Wno-pwms_property" -f sam9x60ek.its sam9x60ek.itb
mkimage: unsupported type Flat Device Tree
make[2]: *** [Makefile:30: sam9x60ek.itb] Error 1
make[1]: *** [package/pkg-generic.mk:250: /home/kevin/atmel/egt/buildroot-at91-linux4sam-sam9x60-2021.04/output/build/dt-overlay-at91-linux4sam-2021.04/.stamp_built] Error 2
make: *** [Makefile:84: _all] Error 2
-
But if I change the directory to dt-overlay and run the mkimage command again, it can generate the itb file without any error message.
kevin@vibrant:cd output/build/dt-overlay-at91-linux4sam-2021.04/
kevin@vibrant:~/atmel/egt/buildroot-at91-linux4sam-sam9x60-2021.04/output/build/dt-overlay-at91-linux4sam-2021.04$ mkimage -D "-i/home/kevin/atmel/egt/buildroot-at91-linux4sam-sam9x60-2021.04/output/build/linux-linux4sam-2021.04/arch/arm/boot/ -i/home/kevin/atmel/egt/buildroot-at91-linux4sam-sam9x60-2021.04/output/build/linux-linux4sam-2021.04/arch/arm/boot/dts -p 1000 -@ -Wno-unit_address_vs_reg -Wno-graph_child_address -Wno-pwms_property" -f sam9x60ek.its sam9x60ek.itb
FIT description: Microchip SAM9X60-EK FIT Image
Created:         Tue Aug 31 09:37:53 2021
-
I did the same test for SAMA5D2-XULT, it also has the same error message while generating itb file. 

Kevin L.
Thanks & Best Rds

**Comment by ehristev** [comment]
Hi,

The way you are describing this, it seems like there is something missing in your build system compared to ours. This can have two causes: either we have something installed that we don't know about (and did not document it, so you can have it as well),
or there is something that you have missed to install in your build system.

Which linux distribution you are using on your host machine ?

**Comment by klmchp** [comment]
Hi ,
My system information is as below (ubuntu-20.04 LTS):
Linux version 5.4.0-81-generic (buildd@lgw01-amd64-052) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)).

I tried to use buildroot-at91-linux4sam_6.2-icp and buildroot-external-microchip-linux4sam_6.2-icp with sama5d2_xplained_graphics_defconfig, it can generate itb file and SD Card image without any errors.
INFO: vfat(boot.vfat): cmd: "mcopy -bsp -i '/home/kevin/atmel/egt/buildroot-at91-linux4sam_6.2-icp/output/images/boot.vfat' '/home/kevin/atmel/egt/buildroot-at91-linux4sam_6.2-icp/output/images/sama5d2_xplained.itb' '::'" (stderr):
INFO: vfat(boot.vfat): adding file 'boot.bin' as 'boot.bin' ...
INFO: vfat(boot.vfat): cmd: "mcopy -bsp -i '/home/kevin/atmel/egt/buildroot-at91-linux4sam_6.2-icp/output/images/boot.vfat' '/home/kevin/atmel/egt/buildroot-at91-linux4sam_6.2-icp/output/images/boot.bin' '::'" (stderr):
INFO: vfat(boot.vfat): adding file 'u-boot.bin' as 'u-boot.bin' ...
INFO: vfat(boot.vfat): cmd: "mcopy -bsp -i '/home/kevin/atmel/egt/buildroot-at91-linux4sam_6.2-icp/output/images/boot.vfat' '/home/kevin/atmel/egt/buildroot-at91-linux4sam_6.2-icp/output/images/u-boot.bin' '::'" (stderr):
INFO: hdimage(sdcard.img): adding partition 'boot' (in MBR) from 'boot.vfat' ...
INFO: hdimage(sdcard.img): adding partition 'rootfs' (in MBR) from 'rootfs.ext4' ...
INFO: hdimage(sdcard.img): writing MBR
 
Kevin L.
Thanks & Best Rds

**Comment by ehristev** [comment]
Hi,

I tried to replicate this build using my laptop Ubuntu 20.04 but on my side it worked fine.
Could you install u-boot-tools
sudo apt install u-boot-tools

and let me know if this solves your problem

**Comment by ehristev** [comment]
Close due to no reply. Please reopen if you still need help.
