### ISSUE TITLE
Not able to login through SSH on SAMAD527 BOARD

### ISSUE THREAD

**Issue by AnshRockstar** [linux4sam/buildroot-external-microchip#14]
hi,
i have enable the dropbear in the networking package of buildroot,in the sshd_config through serial terminal change prohibit password to yes and also i have set the password of the root also but still donot able to do ssh login .please suggest me what i am doing wrong.

**Comment by noglitch** [comment]
Hi,
You should add another user to be able to seamlessly login through ssh.
Doing so in buildroot is special in the sense that /home doesn't exists out of the box.
So:

1. create the /home directory
2. add an user with adduser command
3. verify that /home/<my_new_user> was created by previous command and that the permissions match
4. try to login to the system through ssh with your newly created user
5. if needed on the target, switch to root using the "su -" command

Hope that it helps. Best regards,
  Nicolas

**Comment by ehristev** [comment]
Reopen please if you still need assistance.
Closed due to lack of reply.
