### ISSUE TITLE
Kernel image is missing for th sd card image linux4sam-buildroot-sama5d4_xplained-6.0.img.bz2 (~ 36 MB)

### ISSUE THREAD

**Issue by jensamberg** [linux4sam/buildroot-external-microchip#2]
linux4sam-buildroot-sama5d4_xplained-6.0.img.bz2 (~ 36 MB)
md5: 6825d010b606a7fdf7f66b381a08b49b

**Comment by joshua-henderson** [comment]
The kernel image is indeed in there - just not as a plain zImage like in previous releases.  

That is a bzip2 compressed SD card image.  It contains a partition table and two partitions.  The first partition contains a boot filesystem which then contains some boot files.  One of those files is sama5d4_xplained.itb which is a u-boot fit image that contains both the kernel and device tree blobs.  You can extract the zImage from this file with the u-boot dumpimage tool like:

```
dumpimage -T flat_dt -i sama5d4_xplained.itb -p 0 zImage
```

This will give you the zImage file you're looking for.
