### ISSUE TITLE
No EGT_BENCHMARK_SITE_METHOD declaration

### ISSUE THREAD

**Issue by klmchp** [linux4sam/buildroot-external-microchip#7]
Hi ,
Using buildroot-external-microchip-egt_0.9 with sama5d2_xplained_graphics_defconfig to generate rootfs for sama5d2-xplained and there is erros message as below:
home/kevin/atmel/egt/buildroot-external-microchip-egt_0.9/package/egt-benchmark/egt-benchmark.mk:21: *** EGT_BENCHMARK declares having git sub-modules, but does not use the 'git' method (uses 'https' instead).
Git method declaration should be added to buildroot-external-microchip-egt_0.9/package/egt-benchmark/egt-benchmark.mk
EGT_BENCHMARK_SITE = $(call github,linux4sam,egt-benchmark,$(EGT_BENCHMARK_VERSION))
**EGT_BENCHMARK_SITE_METHOD = git**
EGT_BENCHMARK_GIT_SUBMODULES = YES

**Comment by joshua-henderson** [comment]
This should be fixed with 96e9f77698, which came post egt_0.9 tag and is currently available on the linux4sam_6.2.egt branch.  Please let me know if this does not fix the issue.
