### ISSUE TITLE
mtools is disabled

### ISSUE THREAD

**Issue by ACSdesignservices** [linux4sam/buildroot-external-microchip#8]
Hello,

This is just an FYI and was tested on the 2020.02 and 2020.04 tags on both the default config sama5d2_xplained_graphics_defconfig that is used throughout the examples as well as on the WLSOM.
It appears that in Host utilities, host mtools is not enabled which causes an error running the post build script.
I resolved this by running make menuconfig and enabled mtools in host utilities, ran make again and the post build script ran fine.

Hope you find this useful. Thanks,
Chuck

**Comment by ehristev** [comment]
Hi,
Could you provide a log of the error you are facing when mtools is not enabled ?
Also, what is the host OS ?

Thanks,
Eugen

**Comment by ACSdesignservices** [comment]
Hi Eugen,
Sorry it took a couple days to respond as I had to do a complete reinstall of the buildroot-at91 project to reproduce this. Simply disabling mtools did not cause the error even when I did a make clean.

**OS:**
Linux debian-10a 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

**Steps to reproduce:**
1. mkdir temp
2. cd temp
3. sudo apt update
4. sudo apt upgrade (already up to date)
---- the following commands are straight from the code page for this project ----
5. sudo apt-get install subversion build-essential bison flex gettext \
libncurses5-dev texinfo autoconf automake libtool mercurial git-core \
gperf gawk expat curl cvs libexpat-dev bzr unzip bc python-dev \
wget cpio rsync xxd (everything already installed)
6. git clone https://github.com/linux4sam/buildroot-external-microchip.git -b 2020.02-at91
7. git clone https://github.com/linux4sam/buildroot-at91.git -b 2020.02-at91
8. cd buildroot-at91
9. BR2_EXTERNAL=../buildroot-external-microchip/ make sama5d4_xplained_graphics_defconfig
10. make
11. wait......

**Error:**
>>>   Executing post-image script support/scripts/genimage.sh
/home/chuck/test/buildroot-external-microchip/board/microchip/sama5d4_xplained/genimage.cfg:38: no sub-section title/index for 'config'
INFO: cmd: "mkdir -p "/home/chuck/test/buildroot-at91/output/build/genimage.tmp"" (stderr):
INFO: cmd: "rm -rf "/home/chuck/test/buildroot-at91/output/build/genimage.tmp"/*" (stderr):
INFO: cmd: "mkdir -p "/home/chuck/test/buildroot-at91/output/build/genimage.tmp"" (stderr):
INFO: cmd: "cp -a "/tmp/tmp.3vb62lg2P6" "/home/chuck/test/buildroot-at91/output/build/genimage.tmp/root"" (stderr):
INFO: cmd: "find '/home/chuck/test/buildroot-at91/output/build/genimage.tmp/root' -depth -type d -printf '%P\0' | xargs -0 -I {} touch -r '/tmp/tmp.3vb62lg2P6/{}' '/home/chuck/test/buildroot-at91/output/build/genimage.tmp/root/{}'" (stderr):
INFO: cmd: "mkdir -p "/home/chuck/test/buildroot-at91/output/images"" (stderr):
INFO: vfat(boot.vfat): cmd: "dd if=/dev/zero of="/home/chuck/test/buildroot-at91/output/images/boot.vfat" seek=16777216 count=0 bs=1 2>/dev/null" (stderr):
INFO: vfat(boot.vfat): cmd: "mkdosfs   '/home/chuck/test/buildroot-at91/output/images/boot.vfat'" (stderr):
INFO: vfat(boot.vfat): adding file 'uboot-env.bin' as 'uboot.env' ...
INFO: vfat(boot.vfat): cmd: "MTOOLS_SKIP_CHECK=1 mcopy -bsp -i '/home/chuck/test/buildroot-at91/output/images/boot.vfat' '/home/chuck/test/buildroot-at91/output/images/uboot-env.bin' '::uboot.env'" (stderr):
sh: 1: mcopy: not found
INFO: vfat(boot.vfat): cmd: "rm -f "/home/chuck/test/buildroot-at91/output/images/boot.vfat"" (stderr):
ERROR: vfat(boot.vfat): failed to generate boot.vfat
make: *** [Makefile:829: target-post-image] Error 1

**How to Fix Error:**
1. make menuconfig
2. Host utilities
3. enable mtools
4. esc out and save
5. make

**Success**
>>>   Executing post-image script support/scripts/genimage.sh
/home/chuck/test/buildroot-external-microchip/board/microchip/sama5d4_xplained/genimage.cfg:38: no sub-section title/index for 'config'
INFO: cmd: "mkdir -p "/home/chuck/test/buildroot-at91/output/build/genimage.tmp"" (stderr):
INFO: cmd: "rm -rf "/home/chuck/test/buildroot-at91/output/build/genimage.tmp"/*" (stderr):
INFO: cmd: "mkdir -p "/home/chuck/test/buildroot-at91/output/build/genimage.tmp"" (stderr):
INFO: cmd: "cp -a "/tmp/tmp.wXzbZaH5YE" "/home/chuck/test/buildroot-at91/output/build/genimage.tmp/root"" (stderr):
INFO: cmd: "find '/home/chuck/test/buildroot-at91/output/build/genimage.tmp/root' -depth -type d -printf '%P\0' | xargs -0 -I {} touch -r '/tmp/tmp.wXzbZaH5YE/{}' '/home/chuck/test/buildroot-at91/output/build/genimage.tmp/root/{}'" (stderr):
INFO: cmd: "mkdir -p "/home/chuck/test/buildroot-at91/output/images"" (stderr):
INFO: vfat(boot.vfat): cmd: "dd if=/dev/zero of="/home/chuck/test/buildroot-at91/output/images/boot.vfat" seek=16777216 count=0 bs=1 2>/dev/null" (stderr):
INFO: vfat(boot.vfat): cmd: "mkdosfs   '/home/chuck/test/buildroot-at91/output/images/boot.vfat'" (stderr):
INFO: vfat(boot.vfat): adding file 'uboot-env.bin' as 'uboot.env' ...
INFO: vfat(boot.vfat): cmd: "MTOOLS_SKIP_CHECK=1 mcopy -bsp -i '/home/chuck/test/buildroot-at91/output/images/boot.vfat' '/home/chuck/test/buildroot-at91/output/images/uboot-env.bin' '::uboot.env'" (stderr):
INFO: vfat(boot.vfat): adding file 'sama5d4_xplained.itb' as 'sama5d4_xplained.itb' ...
INFO: vfat(boot.vfat): cmd: "MTOOLS_SKIP_CHECK=1 mcopy -bsp -i '/home/chuck/test/buildroot-at91/output/images/boot.vfat' '/home/chuck/test/buildroot-at91/output/images/sama5d4_xplained.itb' '::'" (stderr):
INFO: vfat(boot.vfat): adding file 'boot.bin' as 'boot.bin' ...
INFO: vfat(boot.vfat): cmd: "MTOOLS_SKIP_CHECK=1 mcopy -bsp -i '/home/chuck/test/buildroot-at91/output/images/boot.vfat' '/home/chuck/test/buildroot-at91/output/images/boot.bin' '::'" (stderr):
INFO: vfat(boot.vfat): adding file 'u-boot.bin' as 'u-boot.bin' ...
INFO: vfat(boot.vfat): cmd: "MTOOLS_SKIP_CHECK=1 mcopy -bsp -i '/home/chuck/test/buildroot-at91/output/images/boot.vfat' '/home/chuck/test/buildroot-at91/output/images/u-boot.bin' '::'" (stderr):
INFO: hdimage(sdcard.img): adding partition 'boot' (in MBR) from 'boot.vfat' ...
INFO: hdimage(sdcard.img): adding partition 'rootfs' (in MBR) from 'rootfs.ext4' ...
INFO: hdimage(sdcard.img): writing MBR

- end -

Hope this is useful - Chuck

**Comment by ehristev** [comment]
Hi,

I created an internal patch for this issue and it will be published to the master branch soon.
If you give me your full name /e-mail, I will add your 
Reported-by: <name> <e-mail> 
tag to the patch.

Thanks for reporting

**Comment by ACSdesignservices** [comment]
Hello,
Glad it helped. Also you can update to say that it builds on Debian
Name: Chuck Strohm
email: cstrohm@acsdesignservices.com
Thanks
