### ISSUE TITLE
AC320005-5 TouchScreen-LCD  resolution correlation

### ISSUE THREAD

**Issue by LuisCRSousa** [linux4sam/buildroot-external-microchip#9]
I've built the EGT example following the build steps and I notice that the touch screen are not configured with the same resolution as the LCD.
I've taken a photo showing the problem using the whiteboard app. The blue lines is where I can touch.

![IMG_1500](https://user-images.githubusercontent.com/8472158/93776932-0caa6980-fc1c-11ea-8eec-57ef50d28cff.jpg)

**Comment by ehristev** [comment]
Hi,

I think you need to open this issue on egt-samples project:
https://github.com/linux4sam/egt-samples

Thanks for reporting !

**Comment by noglitch** [comment]
Well @ehristev, if it happens on all EGT applications, it's probably not due to egt-samples only...
@LuisCRSousa : do you have same behavior with "examples/widgets/widgets" application (changing theme on the top right corner, for instance)?

**Comment by LuisCRSousa** [comment]
> Well @ehristev, if it happens on all EGT applications, it's probably not due to egt-samples only...
> @LuisCRSousa : do you have same behavior with "examples/widgets/widgets" application (changing theme on the top right corner, for instance)?

It happens for all applications that are launched by default. I can't touch theme dropdown because app is registering the touch a few dozens of pixels below and left.

**Comment by LuisCRSousa** [comment]
#https://github.com/linux4sam/egt-samples/issues/1

**Comment by ehristev** [comment]
anything against to close this issue ?
